import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequestPost} from '../functions/api/dialogue.js';
import {polishReply} from '../src/ai-dialogue.js';
const input={caller:'nino',scheme:'prize',expression:'thinking',history:[{speaker:'Você',text:'Olá'}],reference:'Quem organizou?'};
function context(body=input,origin='https://quasehonestos.pages.dev',env={}){return {request:new Request('https://quasehonestos.pages.dev/api/dialogue',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)}),env};}
test('Função recusa outra origem e volta ao offline sem segredo',async()=>{assert.equal((await onRequestPost(context(input,'https://other.example'))).status,403);assert.equal((await onRequestPost(context())).status,503);});
test('Entradas inválidas são rejeitadas antes de consultar Gemini',async()=>{assert.equal((await onRequestPost(context({...input,caller:'fake'},undefined,{GEMINI_API_KEY:'test'}))).status,400);});
test('Resposta Gemini usa segredo no servidor e não o devolve',async()=>{const original=globalThis.fetch;try{globalThis.fetch=async(url,options)=>{assert.equal(options.headers['x-goog-api-key'],'server-only');assert.match(JSON.parse(options.body).systemInstruction.parts[0].text,/Nino/);return Response.json({candidates:[{content:{parts:[{text:JSON.stringify({text:'Minha batata quer saber quem organizou.',decision:'clarify'})}]}}]});};const response=await onRequestPost(context(input,undefined,{GEMINI_API_KEY:'server-only'}));assert.deepEqual(await response.json(),{text:'Minha batata quer saber quem organizou.'});}finally{globalThis.fetch=original;}});
test('Cliente altera só a fala e mantém reserva quando a API falha',async()=>{const reply={speaker:'Nino',text:'Fala local'},a={caller:'nino',scheme:'prize',expression:'thinking',trust:1,stage:'question',log:[{speaker:'Você',text:'Oi'},reply]};assert.equal(await polishReply(a,reply,async()=>new Response('',{status:503})),false);assert.equal(reply.text,'Fala local');assert.equal(await polishReply(a,reply,async()=>Response.json({text:'Oi! Minha batata mandou lembranças.'})),true);assert.equal(a.trust,1);assert.equal(a.stage,'question');});
