import {prepareOperation} from './prepare-operation.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,nextCall,applyMove,finishCall,buy,load,executeScheme,availableMoves,sendUpdateFile,reviewUpdateData} from '../src/engine.js';
import {schemes,furniture,schemeItems} from '../src/data.js';
function started(scheme){const state=fresh();nextCall(state);Object.assign(state.active,{scheme:scheme.id,prepared:true,stage:'pitch',log:[{speaker:'Você',text:scheme.opening},{speaker:'Nino',text:scheme.response}]});return state;}
test('Conversa libera um item; apenas o app correto paga uma vez',()=>{for(const scheme of schemes){const state=started(scheme);assert.equal(executeScheme(state,schemeItems[scheme.id].app),false);for(const id of ['pitch','answer','request']){if(scheme.id==='update'&&id==='request')assert.equal(sendUpdateFile(state),true);assert.equal(applyMove(state,id),true);}if(scheme.id==='update')for(const id of ['nickname','contact','routine'])reviewUpdateData(state,id);assert.equal(state.active.stage,'ready');assert.equal(state.active.outcome,null);assert.equal(state.credits,0);assert.match(state.active.item.token,/^QH-DEMO-/);assert.equal(executeScheme(state,'wrong-app'),false);prepareOperation(state);assert.equal(executeScheme(state,schemeItems[scheme.id].app),true);assert.equal(state.credits,scheme.payout);assert.equal(executeScheme(state,schemeItems[scheme.id].app),false);finishCall(state);assert.equal(state.history[0].earned,scheme.payout);assert.equal(state.history[0].item.app,schemeItems[scheme.id].app);assert.equal(buy(state,furniture[0]),true);assert.equal(buy(state,furniture[0]),false);assert.deepEqual(load({getItem:()=>JSON.stringify(state)}).decor,['plant']);}});
test('Dar tempo para verificar bloqueia o fluxo e não libera crédito',()=>{const state=started(schemes[0]);applyMove(state,'pitch');applyMove(state,'wait');assert.equal(state.active.outcome,'blocked');assert.equal(state.active.item,undefined);assert.equal(executeScheme(state,'wallet'),false);assert.equal(state.credits,0);});
test('Suspensão do fluxo impede pular da abertura para um item',()=>{const state=started(schemes[1]);assert.equal(applyMove(state,'request'),false);assert.equal(applyMove(state,'pressure'),true);assert.equal(applyMove(state,'answer'),true);assert.equal(applyMove(state,'request'),true);assert.equal(state.active.outcome,null);assert.equal(state.active.stage,'question');assert.equal(state.active.item,undefined);assert.equal(executeScheme(state,'support'),false);assert.equal(state.credits,0);});
test('Retomar uma sessão mantém o item e impede pagamento duplicado',()=>{const state=started(schemes[2]);['pitch','answer','request'].forEach(id=>applyMove(state,id));const restored=load({getItem:()=>JSON.stringify(state)});prepareOperation(restored);assert.equal(executeScheme(restored,'club'),true);const again=load({getItem:()=>JSON.stringify(restored)});assert.equal(executeScheme(again,'club'),false);assert.equal(again.credits,schemes[2].payout);});
test('Saldo insuficiente não permite comprar',()=>{const state=fresh();assert.equal(buy(state,furniture[2]),false);assert.equal(state.credits,0);});
