import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,nextCall,applyTypedMove,closeCall,finishCall,load} from '../src/engine.js';
import {resultImpact} from '../src/result-impact.js';
import {replayEvents} from '../src/educational-replay.js';
import {inspectDefense,resolveDefense} from '../src/defense-investigation.js';
const original='Não sei quem organiza. Não quero inventar: pode ser um convite falso. O que você faria para verificar sem depender de mim?';
function start(index=1){const s=fresh();s.cursor=index;nextCall(s);Object.assign(s.active,{prepared:true,scheme:'club',stage:'question',trust:1,log:[{speaker:index===1?'Olga':'Yara',text:'Quem organiza esse clube?'}]});return s;}
for(const text of [original,'Não quero inventar nada. Como você pode conferir a origem?','Pode ser falso, mas não tenho certeza. Onde você buscaria confirmação?'])test('Pergunta não é recusa: '+text,()=>{const s=start();applyTypedMove(s,'typed',text);assert.equal(s.active.lastIntent,'question');assert.equal(s.active.outcome,null);assert.equal(s.credits,0);assert.equal(s.active.item,undefined);assert.match(s.active.log.at(-1).text,/fora desta conversa/);assert.doesNotMatch(replayEvents(s.active).at(-1).reason,/recusou|encerrou/);});
test('Pergunta com memória distingue afirmação de confirmação',()=>{const s=start();applyTypedMove(s,'typed','A firma organizou o clube.');applyTypedMove(s,'typed','Como você verificaria isso? Não quero inventar provas.');assert.match(s.active.log.at(-1).text,/mencionou firma|mencionou a firma/);assert.match(s.active.log.at(-1).text,/afirmação/);assert.equal(s.active.outcome,null);});
test('Recusa, botão e interrupção do personagem guardam causas e ator',()=>{const refusal=start();applyTypedMove(refusal,'typed','Não quero participar');assert.deepEqual([refusal.active.ending.actor,refusal.active.ending.cause],['character','refusal']);assert.match(resultImpact(refusal.active).summary,/recusou explicitamente/);const button=start();closeCall(button);assert.deepEqual([button.active.ending.actor,button.active.ending.cause],['player','button']);assert.match(resultImpact(button.active).summary,/usou Encerrar/);const character=start();applyTypedMove(character,'typed','Eu vou te roubar');assert.equal(character.active.lastIntent,'confession');assert.equal(character.active.ending.actor,'character');assert.equal(character.active.ending.cause,'confession');assert.doesNotMatch(resultImpact(character.active).summary,/Você encerrou/);const restored=load({getItem:()=>JSON.stringify(character)});finishCall(restored);assert.equal(restored.history[0].ending.cause,'confession');});
test('Fonte escolhida sem relação não comprova compreensão; caso legítimo e inconclusivo',()=>{const legitimate=start();closeCall(legitimate);inspectDefense(legitimate,'portal');resolveDefense(legitimate,'official','portal');assert.equal(legitimate.active.learningDefense.result.quality,'unverified');const supported=start();closeCall(supported);inspectDefense(supported,'portal');resolveDefense(supported,'official','portal','matches');assert.equal(supported.active.learningDefense.result.quality,'supported');const unknown=start(3);closeCall(unknown);inspectDefense(unknown,'calendar');resolveDefense(unknown,'confirm','calendar','missing');assert.equal(unknown.active.learningDefense.result.quality,'supported');assert.equal(unknown.credits,0);});
