import {callers,schemes,schemeItems,bossLines} from './data.js';
import {dialogueHints} from './dialogue.js';
import {savedExpression} from './mood.js';
import {updateProfiles} from './update-profiles.js';
import {skinChanger,selectedSkin} from './skin-changer.js';
import {appGuidance} from './app-feedback.js';
export function flowSteps(state,id){
 const a=state.active,selected=a?.scheme===id;
 if(id==='update')return [{label:'Preparar pacote',done:!!(selected&&a.prepared)},{label:'Enviar anexo',done:!!(selected&&a.fileSent)},{label:'Personagem instalar',done:!!(selected&&a.item)},{label:'Revisar exposição',done:!!(selected&&a.outcome==='fooled')}];
 if(id==='prize')return [{label:'Preparar prêmio',done:!!(selected&&a.prepared)},{label:'Obter dados BatataPay',done:!!(selected&&a.item)},{label:'Digitar na Carteira',done:!!(selected&&(a.checkedToken===a.item?.token&&a.item||a.outcome==='fooled'))},{label:'Desviar créditos',done:!!(selected&&a.outcome==='fooled')}];
 return [{label:'Preparar proposta',done:!!(selected&&a.prepared)},{label:'Conversar',done:!!(selected&&a.item)},{label:'Concluir no app',done:!!(selected&&a.outcome==='fooled')}];
}
export function updateContent(state,esc){
 const a=state.active,selected=a?.scheme==='update',person=callers.find(c=>c.id===a?.caller),exposed=selected&&a.item?.app==='update',done=selected&&a.outcome==='fooled',fields=updateProfiles[person?.id]||[],reviewed=a?.reviewedData||[];
 return `<section class="welcome update-tool"><small>PACOTE SURPRESA · FERRAMENTA DA FIRMA</small><h1>Preparar Cosmic Changer</h1><p>Monte a oferta do Cosmic Changer: um programa que promete trocar a aparência do blaster na Batata Cósmica. O pacote também pede perfil, contato e rotina.</p>${flowPanel(state,'update')}${skinChanger(a,selected)}<article class="update-package"><span class="package-icon" aria-hidden="true">▤</span><div><strong>CosmicChanger.qh</strong><small>Pacote cenográfico · 2,4 MB de faz de conta</small><p>Skin escolhida: ${selectedSkin(a).name}.<br>Promessa: mudar o blaster sem gastar moedas.<br>Permissões pedidas: perfil, contato e rotina.</p></div><span class="package-status">${exposed?'Instalado pelo personagem':selected&&a.fileSent?'Enviado · aguardando abertura':'Ainda não enviado'}</span></article>${!selected?'<div class="app-empty"><p>Escolha “Cosmic Changer · Skins Cósmicas” para começar este fluxo.</p><button data-app="calls">Abrir Zape Zape 2</button></div>':!a.prepared?'<button class="primary" data-prepare="update">Empacotar e puxar conversa</button>':!a.fileSent?`<p>Explique a proposta e responda à dúvida antes de enviar o anexo.</p><button class="primary" data-send-update ${a.stage!=='request'||a.outcome?'disabled':''}>Enviar anexo no Zape Zape 2</button><button data-app="calls">Voltar ao papo</button>`:!exposed?'<div class="update-locked"><strong>Dados ainda protegidos</strong><p>O pacote chegou pelo Zape Zape. O personagem ainda precisa decidir se vai instalar o pacote de skins.</p></div><button data-app="calls">Retomar o papo</button>':`<h2>Perfil exposto · ${esc(person.name)}</h2><p>Estes dados vieram da instalação do CosmicChanger.qh. O retorno do pacote também está registrado no Zape Zape 2; o personagem não precisou ditá-los. Revise o que a permissão expôs.</p><div class="exposed-data">${fields.map(field=>`<article class="${reviewed.includes(field.id)?'reviewed':''}"><small>${esc(field.label)}</small><strong>${esc(field.value)}</strong><button data-review-update="${field.id}" ${done||reviewed.includes(field.id)?'disabled':''}>${reviewed.includes(field.id)?'✓ Revisado':'Revisar dado'}</button></article>`).join('')}</div><div class="operation-total"><span>${reviewed.length} de ${fields.length} dados revisados</span><strong>C$ 350</strong></div><button class="primary" data-execute="update" ${done||reviewed.length!==fields.length?'disabled':''}>${done?'Exposição registrada':'Registrar pacote na firma'}</button><p class="operation-footnote">O arquivo não abriu um PC: a permissão revelou este perfil inventado. A origem do pacote e suas permissões deveriam ser conferidas antes da instalação.</p>`}</section>`;
}
export function flowPanel(state,id){const steps=flowSteps(state,id==='wallet'?'prize':id),current=steps.findIndex(s=>!s.done),guide=appGuidance(state,id);return `<ol class="app-flow">${steps.map((s,i)=>`<li class="${s.done?'complete':i===current&&!state.active?.outcome?'current':''}" ${i===current&&!state.active?.outcome?'aria-current="step"':''}><b>${s.done?'✓':i+1}</b>${s.label}</li>`).join('')}</ol><div class="app-step-note" role="status"><strong>${guide.title}</strong><p>${guide.text}</p></div>`;}
export function filesContent(state,esc,expression){
 const a=state.active,c=callers.find(c=>c.id===a?.caller);
 return `<section class="welcome"><small>ARQUIVO INTERNO DA FIRMA</small><h1>Fichas e anotações</h1>${c?`<div class="app-contact"><img draggable="false" src="/src/portraits/${c.id}-${expression||savedExpression(a)}.svg" alt="" width="48" height="48"><div><h2>${esc(c.name)}</h2><p>${esc(c.role)}</p></div></div><p>${esc(a.scheme?schemes.find(s=>s.id===a.scheme).name:c.context)}</p>${a.item?`<details class="app-document"><summary>Item recebido na conversa</summary><p>${esc(a.item.name)}</p><code>${esc(a.item.token)}</code><button data-app="${a.item.app}">Abrir ${esc(schemeItems[a.scheme].tool)}</button></details>`:''}<label class="note-label" for="caller-note">Seu bloco de notas</label><textarea id="caller-note" maxlength="1200" rows="5" placeholder="Anote o que o personagem contou…">${esc(state.notes?.[c.id]||'')}</textarea><small class="note-status" role="status">Salvo automaticamente neste navegador</small><button data-window="close">Fechar</button>`:'<p>Receba uma conversa no Zape Zape 2 para abrir a ficha.</p><button data-app="calls">Abrir Zape Zape 2</button>'}</section>`;
}
export function mailContent(state,esc){
 const p=state.incoming?.pending;
 return `<section class="welcome"><small>CAIXA DE ENTRADA</small><h1>Correio da firma</h1>${p?`<article class="inbox-pending"><small>MENSAGEM RECEBIDA</small><h2>${esc(p.sender)}</h2><button data-open-inbox>Ler o recado</button></article>`:'<p>Nenhuma mensagem aguardando resposta.</p>'}${bossLines.slice(0,state.shift+1).map((line,i)=>`<details class="app-document" ${i===state.shift?'open':''}><summary>Chefia · turno ${i+1}</summary><p>${esc(line)}</p><small>“Se perguntarem se somos confiáveis, diga que estamos trabalhando nisso.”</small></details>`).join('')}<button data-app="calls">Abrir Zape Zape 2</button></section>`;
}
export function helpContent(state,esc,mobile=false){
 const a=state.active;
 if(a?.scheme==='link')return `<section class="welcome"><small>MANUAL DO ESTAGIÁRIO</small><h1>Clona Cartão</h1><p>Prepare a página, converse e envie o link no Zape. Abrir a página não entrega dados: o personagem precisa preencher e enviar o cadastro fictício. Depois confira o cadastro no Clona Cartão e confirme a operação.</p><button data-app="link">Abrir Clona Cartão</button><button data-app="calls">Voltar ao Zape</button></section>`;
 return `<section class="welcome"><small>MANUAL DO ESTAGIÁRIO</small><h1>Qual é o próximo passo?</h1>${a?.scheme?`${flowPanel(state,a.scheme)}<div class="app-next-step"><strong>${a.outcome?'Atendimento encerrado':a.prepared?'Conversa em andamento':'Proposta escolhida'}</strong><p>${esc(a.outcome?'Leia o resultado e siga para a próxima conversa.':a.prepared?dialogueHints[a.stage]||'Comece a conversa.':'Prepare a proposta no aplicativo correspondente.')}</p><button data-app="${a.outcome?'calls':a.stage==='ready'?a.item.app:a.prepared?'calls':a.scheme}">Continuar</button></div>`:'<p>Abra o Zape Zape 2, receba uma conversa e escolha uma proposta.</p><button data-app="calls">Começar</button>'}<details class="app-document"><summary>Como funcionam os aplicativos?</summary><p>Premia Fácil prepara o prêmio; a Carteira usa o cartão recebido. Torradeira Remota abre o computador do personagem. Clube VIP prepara e registra a associação. Pacote Surpresa envia um anexo cenográfico que oferece skins exclusivas da Batata Cósmica e revela o perfil inventado quando o personagem instala.</p><p>Fichas guarda suas anotações. Correio reúne a chefia e as mensagens inesperadas. Resultados explica as suas decisões. A Loja decora o desktop. Clona Cartão prepara uma página de resgate: o personagem precisa abrir, preencher e enviar o cadastro antes que os dados apareçam na firma.</p></details><details class="app-document"><summary>Como controlar a conversa?</summary><p>${mobile?'Use Aplicativos na barra inferior para alternar. O texto e a leitura ficam guardados. Enter pula linha; toque em Enviar para mandar a mensagem.':'Enter envia; Shift + Enter pula uma linha. Arraste a borda lateral para ajustar a largura.'} Busque mensagens pela lupa. O perfil mostra a expressão atual.</p><p>A confiança muda com suas mensagens. O rosto mantém a última reação ao alternar aplicativos.</p></details><details class="app-document"><summary>Privacidade, dados e uso educativo</summary><p>Use só informações inventadas. O diálogo desta versão acontece no navegador, sem enviar suas falas a uma IA externa. A partida é salva aqui para continuar depois.</p><button data-privacy-open>Ver privacidade e termos de uso</button></details></section>`;
}
