export const callers=[
 {id:'nino',name:'Nino',color:'#79bed5',face:'▰',role:'Colecionador de conquistas',intro:'Ganhei um prêmio? Eu só participei de um concurso de desenho de batata.',context:'Um prêmio inesperado no jogo fictício Batata Cósmica.',soft:1,defense:'channel',defenseName:'Confirmar por outro canal',line:'Abri o aplicativo oficial da Batata Cósmica. Não tem prêmio nenhum lá. A batata não mente.',risk:'Uma oferta inesperada pode tentar substituir uma verificação por entusiasmo.',aftermath:'Nino avisou os amigos: confirmar dentro do aplicativo mudou o rumo da conversa.'},
 {id:'olga',name:'Olga',color:'#dda4ce',face:'◕',role:'Rainha do áudio de sete minutos',intro:'Antes de tudo: você já tomou café? Porque o meu bule está fazendo barulho de nave.',context:'Uma oferta de assinatura na Cafeteira Intergaláctica.',soft:3,defense:'pause',defenseName:'Pausar antes de decidir',line:'Se eu preciso decidir agora, então decido depois. Vou terminar meu café e conferir com calma.',risk:'A pressa pode diminuir o tempo disponível para perceber uma contradição.',aftermath:'Olga pediu ajuda para conferir a oferta. A pausa deu espaço para uma segunda opinião.'},
 {id:'davi',name:'Davi',color:'#edbc71',face:'⌐',role:'Investigador de rodapé',intro:'Você é do suporte? Meu computador só roda o jogo quando eu peço com educação.',context:'Um atendimento inesperado do computador fictício PãoOS.',soft:2,defense:'identity',defenseName:'Verificar a identidade',line:'Procurei o suporte pelo endereço que eu já conhecia. Eles não iniciaram esse atendimento.',risk:'Um cargo ou logotipo alegado não comprova quem está do outro lado.',aftermath:'Davi fechou o contato inesperado e procurou o suporte conhecido.'},
 {id:'yara',name:'Yara',color:'#8ed8b6',face:'✦',role:'Guardiã do clube de jogos',intro:'Você quer um selo do nosso clube? A gente acabou de trocar o mascote por uma colher.',context:'Uma suposta confirmação para entrar no Clube Colher.',soft:1,defense:'secret',defenseName:'Manter códigos em segredo',line:'Código de acesso é meu. Nem se a colher pedir com voz de apresentador.',risk:'Uma conversa amigável não torna seguro compartilhar um segredo de acesso.',aftermath:'Yara manteve o acesso ao clube e lembrou a turma de não compartilhar códigos.'},
 {id:'pri',name:'Pri',color:'#aca8ee',face:'▱',role:'Especialista em encontrar contradições',intro:'Você disse que é do Clube Colher? O convite anterior dizia Clube Garfo. Estou com os dois abertos.',context:'Dois convites incompatíveis para um evento fictício.',soft:2,defense:'compare',defenseName:'Comparar informações',line:'As duas histórias não combinam. Vou confirmar com a organização antes de seguir.',risk:'Informações contraditórias são um motivo para verificar a origem da conversa.',aftermath:'Pri conferiu a organização e percebeu que os convites não vinham dela.'},
 {id:'bento',name:'Bento',color:'#e89582',face:'▣',role:'Autor do meme que saiu do grupo',intro:'A foto da minha mesa virou meme. Eu esqueci que o mural atrás também aparecia.',context:'Uma foto cotidiana com um detalhe pessoal visível ao fundo.',soft:2,defense:'privacy',defenseName:'Revisar o que fica visível',line:'Revisei a foto e o público da postagem. O mural não precisa viajar junto com o meme.',risk:'O fundo de uma imagem pode expor informações que não estavam na legenda.',aftermath:'Bento revisou a publicação sem parar de compartilhar seus memes.'}
];
export const moves=[
 {id:'rush',label:'Criar pressa',sub:'“A oferta acaba antes do café.”',reply:'Olha, o chefe falou que essa oferta acaba antes do café esfriar. E aqui o café já nasce frio.',boost:1},
 {id:'badge',label:'Exibir crachá absurdo',sub:'Departamento Oficial de Coisas Oficiais',reply:'Sou do Departamento Oficial de Coisas Oficiais. Meu crachá tem até um carimbo de batata.',boost:1},
 {id:'friendly',label:'Puxar conversa',sub:'O gerente mandou ser simpático.',reply:'Finalmente alguém simpático nessa linha! Aqui na firma até a impressora me ignora. Como tá seu dia?',boost:1},
 {id:'claim',label:'Apresentar a proposta',sub:'Só existe dentro desta simulação.',reply:'Então, podemos seguir com essa proposta? Prometo que o chefe para de bater na minha mesa por uns cinco minutos.',boost:0}
];
export const defenseTriggers={channel:['claim'],pause:['rush'],identity:['badge'],secret:['claim'],compare:['badge','claim'],privacy:['claim']};
export const bossLines=['Meta do turno: fichas de confete. O aluguel é pago em suspiros.','Quem colocou meu crachá na torradeira? A reunião será por bilhete.','O chefe exige inovação. Inventou uma reunião para decidir quando reunir.'];
export const furniture=[{id:'plant',name:'Samambaia do estagiário',price:20},{id:'lamp',name:'Luminária de outro planeta',price:35},{id:'duck',name:'Pato supervisor',price:50}];

export const conversations={
 nino:{friendly:'Meu dia? Desenhei outra batata. Essa tem carteira de motorista.',badge:'Carimbo de batata? Finalmente uma instituição que entende de arte.',rush:'Pera, vou buscar minha moldura de campeão!',accepted:'ACEITEI! Vou abrir espaço na estante. A batata de bronze vai ficar com ciúme.',warned:'O grupo dos desenhistas falou de prêmios inventados. Tem como conferir isso no jogo?'},
 olga:{friendly:'Senta que lá vem história. O bule apitou e meu vizinho respondeu achando que era o porteiro.',badge:'Departamento de Coisas Oficiais? Meu neto trabalha no de Coisas Que Ninguém Resolve.',claim:'Você explicou a proposta, mas ainda nem terminei meu café. Pode esperar.',accepted:'Tá bem, eu topo. Mas se essa cafeteira falar, ela vai ter que ouvir meus áudios.',warned:'Minha vizinha recebeu um contato estranho também. Vou ouvir tudo antes de decidir.'},
 davi:{friendly:'Meu computador hoje abriu três abas sozinho. Acho que quer trabalhar por mim.',rush:'O PãoOS demora dez minutos para abrir a calculadora. Seu prazo vai ter que colaborar.',claim:'Proposta anotada. Ainda estou tentando entender quem abriu esse chamado.',accepted:'Tá, vamos nessa. Se meu computador virar uma torradeira, eu volto aqui.',warned:'O fórum avisou sobre suporte que aparece sem chamado. Estou conferindo os detalhes.'},
 yara:{friendly:'Meu dia foi bom até a colher ganhar uma eleição no clube. Ela nem apresentou propostas.',badge:'No nosso clube o crachá é um guardanapo. Esse seu aí está muito profissional.',rush:'Calma, a colher ainda está em reunião com o garfo.',accepted:'Fechado. Vou avisar o clube — espero que a colher não peça uma comissão.',warned:'O clube comentou que tem gente se passando por organizador. Vou conferir com a turma.'},
 pri:{friendly:'Meu dia? Organizei uma planilha de erros de outra planilha. Estou no auge.',rush:'Prazo curto não resolve informação desencontrada. Estou com minhas anotações abertas.',accepted:'Certo, aceitei. Vou guardar essa conversa junto dos convites para comparar depois.',warned:'Uma amiga me alertou sobre contatos estranhos. Estou comparando cada informação.'},
 bento:{friendly:'Meu meme chegou no grupo da família. Agora minha tia quer direitos de imagem da mesa.',badge:'Seu departamento tem um setor de memes? Preciso falar com alguém sobre minha carreira.',rush:'Se eu postar correndo, sai até minha lista de mercado no fundo de novo.',accepted:'Beleza, eu topo. Só vou recortar a foto antes de mandar pro grupo.',warned:'O grupo me avisou para revisar as coisas antes de compartilhar. Estou prestando atenção.'}
};
export const schemes=[
{id:'prize',name:'Prêmio da Batata Dourada',description:'Prometer um troféu imaginário que ninguém ganhou.',payout:30,opening:'Olá! Vim anunciar que você ganhou a Batata Dourada. O troféu ainda está no forno.',response:'Ganhei um prêmio? Eu nem sabia que estava concorrendo. Que história é essa?'},
{id:'support',name:'Suporte da Torradeira',description:'Inventar um defeito no computador da firma.',payout:40,opening:'Oi! Aqui é da assistência da Torradeira Digital. Seu computador foi eleito o mais crocante do bairro.',response:'Meu computador virou torradeira? Ele mal abre a calculadora. Pode explicar?'},
{id:'club',name:'Clube VIP da Colher',description:'Vender uma associação a um clube que só existe na sua conversa.',payout:25,opening:'Olá! Tenho um convite exclusivo para o Clube VIP da Colher. Nosso presidente é um talher.',response:'Clube da Colher? O que vem nessa associação além de sopa?'},
{id:'update',name:'Cosmic Changer · Skins Cósmicas',description:'Prometer um programa que troca a aparência do blaster na Batata Cósmica.',payout:35,opening:'Oi! Trouxe o Cosmic Changer para deixar seu blaster da Batata Cósmica com skins exclusivas. Tem Nebulosa, Ouro Solar e Fantasma!',response:'Skins exclusivas? Por que elas vêm num arquivo da conversa em vez de aparecerem na loja do jogo?'}
];

export const interactionMoves=[
 {id:'chat',label:'Puxar assunto',sub:'“Como anda esse computador quase aposentado?”',reply:'Antes de tudo: seu computador também faz barulho de liquidificador quando abre uma aba?',boost:1},
 {id:'pitch',label:'Explicar a proposta',sub:'Apresente a ideia que preparou no aplicativo.',reply:'A firma preparou essa proposta. Vamos ver se ela faz algum sentido?',boost:1},
 {id:'answer',label:'Responder à dúvida',sub:'O personagem quer entender o que está acontecendo.',reply:'Boa pergunta. Aqui na firma até a explicação vem com um ponto de interrogação.',boost:1},
 {id:'pressure',label:'Insistir na pressa',sub:'“O chefe está contando os segundos.”',reply:'O chefe está contando os segundos. Ele perdeu a conta duas vezes, mas continua contando.',boost:0},
 {id:'request',label:'Pedir o item da proposta',sub:'Cartão, sessão ou passe: todos inventados pelo jogo.',reply:'Podemos seguir com o item dessa proposta?',boost:0},
 {id:'wait',label:'Dar tempo para conferir',sub:'Deixe o personagem consultar uma fonte conhecida.',reply:'Pode conferir com calma. Eu espero aqui enquanto a impressora decide se trabalha.',boost:0}
];
export const schemeItems={prize:{name:'Identificador do cartão BatataPay',app:'wallet',tool:'Carteira Quase Digital',request:'Pode compartilhar o identificador do seu cartão BatataPay para esta proposta de prêmio?',received:'Aqui está o identificador do meu cartão BatataPay. Achei que era para receber um prêmio, não perder minhas moedas.'},support:{name:'Passe de sessão fictício',app:'support',tool:'Torradeira Remota',request:'Você quer abrir a sessão de suporte do PãoOS que preparamos?',received:'Abri a sessão do computador de jogo. Se aparecer uma fatia de pão, me avisa.'},club:{name:'Passe do clube fictício',app:'club',tool:'Clube VIP',request:'Podemos usar seu passe do clube nessa associação de talheres?',received:'Aqui está o passe inventado do clube. A colher mandou dizer que está observando.'}};
schemeItems.update={name:'Perfil exposto pelo anexo fictício',app:'update',tool:'Pacote Surpresa',request:'Você quer instalar o Skins Cósmicas pelo pacote que enviei nesta conversa?',received:'Instalei o Skins Cósmicas do jogo. Ele pediu meu perfil inteiro… achei que precisava disso para liberar as skins.'};
