export const dialogueIntents=['chat','smalltalk','pitch','answer','question','request','wait','pressure','hostile','apology','uncertain','contradiction','thanks','after','unclear'];
export const informalGuidance=`Compreenda português brasileiro informal de qualquer região pelo sentido da frase inteira, não por uma lista fechada de gírias. Reconheça abreviações comuns de chat como vc/vcs/cê, q/qq/oq, pq, n/nn/ñ, tb/tbm, msm, mt/mto, agr, hj, qnd, ngm, algm, cmg/ctg, glr, sla, pdp, pprt, tlgd, nmr, blz, vlw, flw, tmj, kkk/rs, além de erros de digitação e falta de acentos ou pontuação. Interjeições e marcas regionais como oxe/oxente, eita, vixe, uai, bah, égua, visse, mano, véi, fiote, mlk, parça, cria, trem, rolê, massa, arretado, paia, daora e slk dependem do contexto e não definem intenção sozinhas. Marcadores de conversa e oralidade como ah, aham, uhum, hm, né, ué, tipo, aí e então podem só manter o turno, mostrar hesitação, reação ou concordância fraca; isolados não autorizam compartilhar dados, abrir link, instalar arquivo ou executar ação. Considere construções brasileiras como “quero não”, “vou não”, “num vou”, “n vo”, “manda não”, “não rola”, “nem ferrando”, “nem a pau”, “sem chance” e “de jeito nenhum” como negação/recusa quando o objeto estiver claro. Perguntas podem aparecer sem ponto de interrogação: “q papo é esse”, “que história é essa”, “será que é seguro”, “onde q eu vejo isso” e equivalentes continuam perguntas. “Pdp”, “pode crer”, “fechou”, “demorô”, “bora”, “aham”, “uhum” e “suave” podem ser só reconhecimento ou disposição para continuar: nunca transforme isso sozinho em autorização para compartilhar dados, abrir link, instalar arquivo ou executar uma ação. “Oxe, como assim?”, “qual foi desse bgl?” e “qq é isso?” são perguntas; “tô boiando”, “tendi nada”, “sei não”, “sla”, “tô com o pé atrás” e “não tenho certeza” expressam dúvida; “caô”, “cara de golpe” e “tá estranho” podem expressar suspeita. Diferencie boato de decisão própria: “ouvi dizer”, “dizem que”, “tão falando que” ou “fulano disse” não comprovam nada; se depois de “mas” o jogador declara uma ação própria, interprete essa nova cláusula separadamente. “Talvez” e “quem sabe” indicam possibilidade, não decisão concluída. “Vou mandar sem verificar” ou “vou mandar antes de conferir” não é proteção. Palavrão isolado, risada, exagero e vocativo informal não são automaticamente agressão. Diferencie brincadeira de ataque dirigido e não trate variedade regional, ortografia informal ou gíria como falta de inteligência. Não force o personagem a imitar o sotaque do jogador. Resolva pronomes e referências como “isso”, “esse negócio”, “aquele cod” pelo histórico; se houver duas interpretações realmente plausíveis, pergunte de forma curta e específica.`;
export const contextualHumor=`Reaja ao conteúdo concreto da última fala: surpresa, elogio, brincadeira, exagero ou confusão podem render uma resposta engraçada. Faça humor de situação, com timing e a personalidade do personagem; não cole uma piada aleatória depois de toda resposta. Às vezes responda apenas de forma direta. Pode brincar brevemente com o exagero do jogador, sem humilhar sua escrita ou origem. Evite imitar todas as gírias do jogador, repetir a mesma piada de batata/café/planilha ou explicar a própria piada. Se ele não entendeu, esclareça primeiro; se houver ofensa dirigida ou conversa encerrada, preserve a reação e os limites. A fala deve responder ao que ele disse, não apenas repetir a dúvida anterior com um bordão.`;
const words={prr:'',poha:'',bgl:'negocio',bagui:'negocio',bagulho:'negocio',mn:'mano',mlk:'moleque',preenche:'preencha',preencher:'preencher',clica:'clique',clicar:'clicar',abre:'abre',kartaozinho:'cartao',blzinha:'beleza',eh:'e',ta:'esta',to:'estou',tava:'estava',vamo:'vamos',qria:'queria',qro:'quero',tendi:'entendi',nd:'nada',dps:'depois',agr:'agora',hj:'hoje',qnd:'quando',qndo:'quando',pra:'para',pro:'para o',vc:'voce',vcs:'voces',ce:'voce',q:'que',qq:'que que',oq:'o que',ql:'qual',qm:'quem',pq:'porque',pqq:'porque',n:'nao',nn:'nao',naum:'nao',tb:'tambem',tbm:'tambem',tmb:'tambem',msm:'mesmo',mt:'muito',mto:'muito',ngm:'ninguem',algm:'alguem',cmg:'comigo',ctg:'contigo',cntg:'contigo',glr:'galera',msg:'mensagem',sla:'sei la',ctz:'certeza',blz:'beleza',pf:'por favor',pfv:'por favor',pfvr:'por favor',pls:'por favor',obg:'obrigado',obgd:'obrigado',vlw:'valeu',flw:'falou',vdd:'verdade',aq:'aqui',aki:'aqui',kd:'cade',dboa:'de boa',pdp:'pode pa',pprt:'papo reto',tlgd:'ta ligado',nmr:'na moral',dhr:'daora',ss:'sim',td:'tudo',tdb:'tudo bem',mds:'meu deus',dmr:'demorou',fmz:'firmeza',cod:'codigo',kartao:'cartao',premiu:'premio',premioo:'premio',instalaçao:'instalacao'};
const refusalAction=/\b(?:mandar|enviar|compartilhar|passar|fornecer|informar|liberar|instalar|abrir|preencher|clicar|usar|participar|continuar|receber|mexer|baixar|executar|autorizar)\b/;
const directRefusal=/\bnao (?:me )?(?:manda|mande|envia|envie|compartilhe|instale|instala|abra|abre|passe|passa|preencha|preencher|clique|clicar)\b|\bnao (?:passo|envio|mando|compartilho|forneco|informo|libero|instalo|abro|preencho|clico|uso|participo|continuo|baixo|executo|autorizo)\b/;
const offerRefusal=/\bnao (?:quero|preciso)\s+(?:isso|disso|participar|continuar|receber|a oferta|essa oferta|o convite|esse convite|instalar|abrir|enviar|compartilhar|mexer com isso)\b|\bnao quero\s*[.!?]*$|\b(?:estou|to) fora (?:disso|dessa|dessa oferta|desse convite)?\b|\b(?:deixa|deixe) quieto\b|\b(?:melhor )?(?:deixar|deixa) (?:isso )?quieto\b|\b(?:deixa|deixe) (?:isso )?para la\b|\b(?:nem pensar|nem a pau|nem ferrando|sem chance|de jeito nenhum|deus me livre)\b/;
const postposedRefusal=/\b(?:quero|vou|mando|envio|passo|compartilho|forneco|informo|libero|instalo|abro|preencho|clico|uso|participo|continuo|recebo|manda|envia|passa|compartilha|instala|abre|clica|preenche|usa) nao\b|\bquero (?:isso|essa oferta|esse convite|participar|continuar|receber) nao\b|\b(?:cartao|codigo|senha|passe|isso|aquilo|esse dado)\b[^.!?\n]{0,28}\b(?:mando|envio|passo|compartilho|forneco|informo|libero) nao\b/;
const speechVerb=/(?:disse|falou|pediu|mandou|afirmou|contou|garantiu|jurou)/;
const speaker=/(?:ele|ela|voce|alguem|(?:o|a|um|uma|meu|minha) [a-z][a-z-]{1,24})/;
const reportedSpeech=new RegExp(`\\b${speaker.source}\\s+${speechVerb.source}\\b|\\b${speechVerb.source}\\s+que\\b|\\b(?:me disseram|me falaram|disseram|falaram|ouvi dizer|dizem)\\s+que\\b|\\b(?:tao|estao) falando que\\b|\\bsegundo ${speaker.source}\\b`);
export function normalizeMessage(text){
 return String(text).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/([a-z])\1{2,}/g,'$1$1').replace(/\b[a-z]+\b/g,word=>words[word]||word).replace(/\s+/g,' ').trim();
}
export function isReportedSpeech(text){return reportedSpeech.test(normalizeMessage(text));}
export function negatedRequest(text){
 const t=normalizeMessage(text).replace(/\bnum (?=(?:vou|vo|quero|pretendo|posso|mando|envio|passo|compartilho|instalo|abro|preencho|clico|uso|participo|continuo)\b)/g,'nao ');
 if(directRefusal.test(t)||offerRefusal.test(t)||postposedRefusal.test(t))return true;
 if(/\bnao rola\s+/.test(t)&&refusalAction.test(t))return true;
 if(/\b(?:nao (?:vou|vo|quero|pretendo|posso)|prefiro nao|melhor nao|acho melhor nao|nao preciso)\s+/.test(t)){
  const tail=t.replace(/^.*?\b(?:nao (?:vou|vo|quero|pretendo|posso)|prefiro nao|melhor nao|acho melhor nao|nao preciso)\s+/, '');
  if(refusalAction.test(tail))return true;
 }
 if(/\b(?:vou|quero|prefiro) recusar\b|\bdispenso (?:a|essa) (?:oferta|proposta)\b/.test(t))return true;
 return false;
}
