export const compactScreen=(width,height=Infinity,touch=false)=>touch&&width<=1000;
export function readingPosition(previous,nextCount){
 if(!previous||previous.bottom)return {follow:true,unread:0};
 return {follow:false,unread:Math.max(0,(previous.unread||0)+nextCount-(previous.count||0))};
}
export function viewportLayout({width,height,visualHeight=height,offsetTop=0,scale=1,focused=false,touch=false}){
 return {height:scale===1?Math.round(visualHeight):height,top:scale===1?Math.round(offsetTop):0,keyboard:compactScreen(width,height,touch)&&focused&&scale===1&&height-visualHeight>100};
}
export function mobileNavigation(apps,current,{expanded=false,pending=false,unread=0}={},icon=()=> ''){
 return `<nav class="mobile-dock" aria-label="Aplicativos do Trambique OS"><button data-app="calls" aria-current="${current==='calls'?'page':'false'}">${icon('calls')}<span>Zape${unread?` · ${unread}`:''}</span></button><button data-mobile-apps aria-expanded="${expanded}"><svg class="os-app-grid" viewBox="0 0 32 32" aria-hidden="true"><rect x="4" y="4" width="10" height="10" rx="2" fill="#edc58a"/><rect x="18" y="4" width="10" height="10" rx="2" fill="#89c8b8"/><rect x="4" y="18" width="10" height="10" rx="2" fill="#93becf"/><rect x="18" y="18" width="10" height="10" rx="2" fill="#c6dca1"/></svg><span>Aplicativos</span></button><button data-mobile-inbox aria-label="Correio${pending?' · mensagem nova':''}">${icon('boss')}<span>Correio${pending?' · novo':''}</span></button></nav>${expanded?`<section class="mobile-app-switcher" role="dialog" aria-modal="true" aria-label="Alternar aplicativo"><header><strong>Trambique OS</strong><button data-mobile-apps aria-label="Fechar alternador">×</button></header><p>O trabalho fica onde você deixou. Até o café.</p><div>${apps.map(([id,,name])=>`<button data-app="${id}" aria-current="${id===current?'page':'false'}">${icon(id)}<span>${name}${id==='boss'&&pending?' · novo recado':id==='calls'&&unread?' · mensagens novas':''}</span></button>`).join('')}</div><footer class="mobile-utilities"><button data-sound-panel>Sons do computador</button><button data-privacy-open>Privacidade e dados locais</button><button data-network-toggle>Internet da firma</button></footer></section>`:''}`;
}
export function installViewport(onWidthChange){
 let lastWidth=innerWidth,baselineHeight=innerHeight;
 const update=()=>{const v=window.visualViewport,focused=!!document.activeElement?.matches('input,textarea,select');if(v&&v.scale!==1)return;if(lastWidth!==innerWidth||!focused)baselineHeight=innerHeight;const layout=viewportLayout({width:innerWidth,height:baselineHeight,visualHeight:v?.height||innerHeight,offsetTop:v?.offsetTop,scale:v?.scale,focused,touch:matchMedia('(pointer: coarse)').matches});document.documentElement.style.setProperty('--qh-view-height',layout.height+'px');document.documentElement.style.setProperty('--qh-view-top',layout.top+'px');document.body.classList.toggle('keyboard-open',layout.keyboard);if(lastWidth!==innerWidth){lastWidth=innerWidth;onWidthChange();}};
 matchMedia('(pointer: coarse)').addEventListener('change',()=>{update();onWidthChange();});window.addEventListener('resize',update);window.visualViewport?.addEventListener('resize',update);window.visualViewport?.addEventListener('scroll',update);document.addEventListener('focusin',update);document.addEventListener('focusout',()=>requestAnimationFrame(update));update();return update;
}
